name: CI

on:
  push:
  pull_request:

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  sast-semgrep:
    uses: ./.github/workflows/semgrep.yml
    with:
      working-dir: app
      exclude: '["app/bin", "app/include", "app/lib"]'
      ghas-sarif-category: app-semgrep
